language: python

python:
  - "3.7"

notifications:
  email:
    on_success: never

install:
  - pip install mkdocs mkdocs-material
  - echo -e "machine github.com\n  login ${GITHUB_API_KEY}" > ~/.netrc

script:
  - mkdocs gh-deploy --force --clean

branches:
  only:
    - master