site_name: 课程资料
nav:
  - 首页: index.md
  - 网页设计与制作: web.md
  - 网页设计与制作: 
    - 课程概述: web/introduction.md
  - 数字媒体安全应用与实践: apdms.md
  - 数字媒体安全应用与实践:
    - 课程概述: apdms/introduction.md
    - Flask 简介: apdms/flask-intro.md


# Repository
repo_name: 'anjingcuc/courses-wiki'
repo_url: 'https://github.com/anjingcuc/courses-wiki'

theme:
  name: null
  custom_dir: "material"
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  logo:
    icon: "school"
  feature:
    tabs: true
  font:
    text: "Fira Sans"
    code: "Fira Mono"
