site_name: 课程资料
nav:
  - 首页: index.md
  - 计算机安全与维护: cms.md
  - 计算机安全与维护:
      - 课件: cms/slides.md
      - Windows 安装实验: cms/windows-install-homework.md
      - Windows 组件实验: cms/windows-components.md
      - 恶意代码实验: cms/malware.md
      - 数据恢复实验: cms/data-recovery-homework.md
      - 脚本实验: cms/scripts-homework.md
  - 网页设计与制作: web.md
  - 网页设计与制作:
      - 作业: web/homework.md
      - 课程概述: web/introduction.md
      - HTML 元素详解: web/html-elements.md
      - CSS 样式表: web/css-first-steps.md
      - CSS 文本样式: web/css-text.md
      - CSS 盒子样式: web/css-box.md
      - CSS 布局: web/css-layout.md
      - JavaScript 初探: web/javascript-introduction.md
      - JavaScript 基础: web/javascript-basic.md
      - JavaScript 结构化代码: web/javascript-blocks.md
      - 面向对象的 JavaScript: web/javascript-oo.md
      - JavaScript API: web/javascript-API.md
      - Bootstrap: web/bootstrap.md
      - jQuery: web/jQuery.md
  - 数字媒体安全应用与实践: apdms.md
  - 数字媒体安全应用与实践:
      - 课程概述: apdms/introduction.md
      - Flask 简介: apdms/flask-intro.md
      - Flask 初探: apdms/flask-getting-start.md
      - Jinja2 模板: apdms/jinja2.md
      - WTForms 表单: apdms/wtforms.md
  - 临时代课: substitute.md
  - 临时代课: 
      - 软件项目安全开发生命周期-WinDBG: substitute/windbg.md 
      - 软件项目安全开发生命周期-WinDBG脚本: substitute/windbg-script.md 

# Repository
repo_name: "anjingcuc/courses-wiki"
repo_url: "https://github.com/anjingcuc/courses-wiki"

theme:
  name: null
  custom_dir: "material"
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  logo:
    icon: "school"
  feature:
    tabs: true
  font:
    text: "Fira Sans"
    code: "Fira Mono"
