site_name: 课程资料
nav:
  - 首页: index.md
  - 计算机安全与维护: cms.md
  - 计算机安全与维护:
      - 课程概述: cms/introduction.md
      - Virtualbox: cms/virtualbox.md
      - Windows 安装: cms/windows-install.md
      - Windows 用户账户: cms/windows-accounts.md
      - Windows 进程线程: cms/windows-process-thread.md
      - Windows 服务: cms/windows-service.md
      - 恶意代码简介: cms/malware-introduction.md
      - 恶意代码分析: cms/malware-analysis.md
      - 数据恢复: cms/data-recovery.md
      - 自动化与脚本: cms/cmd-scripts.md
  - 网页设计与制作: web.md
  - 网页设计与制作:
      - 课程概述: web/introduction.md
      - HTML 元素详解: web/html-elements.md
      - CSS 样式表: web/css-first-steps.md
      - CSS 文本样式: web/css-text.md
      - CSS 盒子样式: web/css-box.md
      - CSS 布局: web/css-layout.md
      - JavaScript 初探: web/javascript-introduction.md
  - 数字媒体安全应用与实践: apdms.md
  - 数字媒体安全应用与实践:
      - 课程概述: apdms/introduction.md
      - Flask 简介: apdms/flask-intro.md
      - Flask 初探: apdms/flask-getting-start.md
      - Jinja2 模板: apdms/jinja2.md
      - WTForms 表单: apdms/wtforms.md

# Repository
repo_name: "anjingcuc/courses-wiki"
repo_url: "https://github.com/anjingcuc/courses-wiki"

theme:
  name: null
  custom_dir: "material"
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  logo:
    icon: "school"
  feature:
    tabs: true
  font:
    text: "Fira Sans"
    code: "Fira Mono"
